# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TarkovTools.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHBoxLayout, QLabel, QLayout, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1755, 907)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1755, 907))
        MainWindow.setMaximumSize(QSize(1755, 907))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"resources/thumbnail.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionThese_Do_Nothing = QAction(MainWindow)
        self.actionThese_Do_Nothing.setObjectName(u"actionThese_Do_Nothing")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 9, 1741, 851))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.QuestCreator = QWidget()
        self.QuestCreator.setObjectName(u"QuestCreator")
        self.FailMessage = QTextEdit(self.QuestCreator)
        self.FailMessage.setObjectName(u"FailMessage")
        self.FailMessage.setGeometry(QRect(350, 320, 441, 201))
        self.ChangeMessage = QTextEdit(self.QuestCreator)
        self.ChangeMessage.setObjectName(u"ChangeMessage")
        self.ChangeMessage.setGeometry(QRect(810, 320, 441, 201))
        self.SecretQuest = QCheckBox(self.QuestCreator)
        self.SecretQuest.setObjectName(u"SecretQuest")
        self.SecretQuest.setGeometry(QRect(770, 30, 101, 20))
        self.SecretQuest.setChecked(False)
        self.Description = QTextEdit(self.QuestCreator)
        self.Description.setObjectName(u"Description")
        self.Description.setGeometry(QRect(350, 100, 441, 201))
        self.Type = QComboBox(self.QuestCreator)
        self.Type.setObjectName(u"Type")
        self.Type.setGeometry(QRect(1050, 60, 201, 21))
        self.tabWidget_2 = QTabWidget(self.QuestCreator)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(1270, 0, 461, 791))
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.AvailableForStartLevelRequirement = QLineEdit(self.tab_4)
        self.AvailableForStartLevelRequirement.setObjectName(u"AvailableForStartLevelRequirement")
        self.AvailableForStartLevelRequirement.setGeometry(QRect(10, 20, 111, 21))
        self.AvailableForStartLevelRequirement.setClearButtonEnabled(True)
        self.AvailableForStartLevelRequirementCompare = QComboBox(self.tab_4)
        self.AvailableForStartLevelRequirementCompare.setObjectName(u"AvailableForStartLevelRequirementCompare")
        self.AvailableForStartLevelRequirementCompare.setGeometry(QRect(310, 20, 121, 22))
        self.line_4 = QFrame(self.tab_4)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 40, 451, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.AvailableForStartQuestId = QLineEdit(self.tab_4)
        self.AvailableForStartQuestId.setObjectName(u"AvailableForStartQuestId")
        self.AvailableForStartQuestId.setGeometry(QRect(10, 70, 111, 21))
        self.AvailableForStartQuestId.setClearButtonEnabled(True)
        self.AvailableForStartAddToList = QPushButton(self.tab_4)
        self.AvailableForStartAddToList.setObjectName(u"AvailableForStartAddToList")
        self.AvailableForStartAddToList.setGeometry(QRect(310, 70, 121, 24))
        self.AvailableForStartDynamicLocaleLevel = QCheckBox(self.tab_4)
        self.AvailableForStartDynamicLocaleLevel.setObjectName(u"AvailableForStartDynamicLocaleLevel")
        self.AvailableForStartDynamicLocaleLevel.setGeometry(QRect(170, 20, 111, 20))
        self.AvailableForStartDynamicLocaleLevel.setChecked(False)
        self.AvailableForStartDynamicLocaleQuest = QCheckBox(self.tab_4)
        self.AvailableForStartDynamicLocaleQuest.setObjectName(u"AvailableForStartDynamicLocaleQuest")
        self.AvailableForStartDynamicLocaleQuest.setGeometry(QRect(170, 70, 111, 20))
        self.AvailableForStartDynamicLocaleQuest.setChecked(False)
        self.AvailableForStartStatus = QComboBox(self.tab_4)
        self.AvailableForStartStatus.setObjectName(u"AvailableForStartStatus")
        self.AvailableForStartStatus.setGeometry(QRect(10, 100, 111, 22))
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 0, 49, 16))
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 111, 16))
        self.StartQuestWidget = QListWidget(self.tab_4)
        self.StartQuestWidget.setObjectName(u"StartQuestWidget")
        self.StartQuestWidget.setGeometry(QRect(0, 130, 451, 151))
        self.AvailableForStartRemoveFromList = QPushButton(self.tab_4)
        self.AvailableForStartRemoveFromList.setObjectName(u"AvailableForStartRemoveFromList")
        self.AvailableForStartRemoveFromList.setGeometry(QRect(310, 100, 121, 24))
        self.StartLoyaltyWidget = QListWidget(self.tab_4)
        self.StartLoyaltyWidget.setObjectName(u"StartLoyaltyWidget")
        self.StartLoyaltyWidget.setGeometry(QRect(0, 370, 451, 211))
        self.AvailableForStartLoyaltyRemoveFromList = QPushButton(self.tab_4)
        self.AvailableForStartLoyaltyRemoveFromList.setObjectName(u"AvailableForStartLoyaltyRemoveFromList")
        self.AvailableForStartLoyaltyRemoveFromList.setGeometry(QRect(310, 340, 121, 24))
        self.AvailableForStartLoyaltyAddToList = QPushButton(self.tab_4)
        self.AvailableForStartLoyaltyAddToList.setObjectName(u"AvailableForStartLoyaltyAddToList")
        self.AvailableForStartLoyaltyAddToList.setGeometry(QRect(310, 310, 121, 24))
        self.AvailableForStartTraderComboBox = QComboBox(self.tab_4)
        self.AvailableForStartTraderComboBox.setObjectName(u"AvailableForStartTraderComboBox")
        self.AvailableForStartTraderComboBox.setGeometry(QRect(10, 310, 111, 22))
        self.AvailableForStartLoyaltyDynamicLocaleQuest = QCheckBox(self.tab_4)
        self.AvailableForStartLoyaltyDynamicLocaleQuest.setObjectName(u"AvailableForStartLoyaltyDynamicLocaleQuest")
        self.AvailableForStartLoyaltyDynamicLocaleQuest.setGeometry(QRect(170, 310, 111, 20))
        self.AvailableForStartLoyaltyDynamicLocaleQuest.setChecked(False)
        self.label_10 = QLabel(self.tab_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 290, 151, 16))
        self.AvailableCompareLoyaltyComboBox = QComboBox(self.tab_4)
        self.AvailableCompareLoyaltyComboBox.setObjectName(u"AvailableCompareLoyaltyComboBox")
        self.AvailableCompareLoyaltyComboBox.setGeometry(QRect(170, 340, 121, 21))
        self.AvailableCompareLoyaltyComboBox.setEditable(False)
        self.AvailableCompareLoyaltyComboBox.setModelColumn(0)
        self.AvailableForStartLoyaltyValue = QLineEdit(self.tab_4)
        self.AvailableForStartLoyaltyValue.setObjectName(u"AvailableForStartLoyaltyValue")
        self.AvailableForStartLoyaltyValue.setGeometry(QRect(10, 340, 111, 21))
        self.AvailableForStartLoyaltyValue.setClearButtonEnabled(True)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.lineEdit_14 = QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(9, 906, 132, 21))
        self.lineEdit_14.setClearButtonEnabled(True)
        self.checkBox_10 = QCheckBox(self.tab_3)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(9, 933, 212, 20))
        self.checkBox_10.setChecked(False)
        self.tabWidget_5 = QTabWidget(self.tab_3)
        self.tabWidget_5.setObjectName(u"tabWidget_5")
        self.tabWidget_5.setGeometry(QRect(0, 0, 461, 771))
        self.tabWidget_5.setTabBarAutoHide(False)
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.label = QLabel(self.tab_11)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 49, 16))
        self.FinishLoyaltyDynamicLocale = QCheckBox(self.tab_11)
        self.FinishLoyaltyDynamicLocale.setObjectName(u"FinishLoyaltyDynamicLocale")
        self.FinishLoyaltyDynamicLocale.setGeometry(QRect(220, 20, 111, 20))
        self.FinishLoyaltyValue = QLineEdit(self.tab_11)
        self.FinishLoyaltyValue.setObjectName(u"FinishLoyaltyValue")
        self.FinishLoyaltyValue.setGeometry(QRect(140, 20, 71, 21))
        self.FinishLoyaltyValue.setClearButtonEnabled(True)
        self.FinishLoyaltyCompare = QComboBox(self.tab_11)
        self.FinishLoyaltyCompare.setObjectName(u"FinishLoyaltyCompare")
        self.FinishLoyaltyCompare.setGeometry(QRect(330, 20, 121, 22))
        self.FinishLoyaltyRemoveFromList = QPushButton(self.tab_11)
        self.FinishLoyaltyRemoveFromList.setObjectName(u"FinishLoyaltyRemoveFromList")
        self.FinishLoyaltyRemoveFromList.setGeometry(QRect(320, 230, 121, 24))
        self.FinishLoyaltyWidget = QListWidget(self.tab_11)
        self.FinishLoyaltyWidget.setObjectName(u"FinishLoyaltyWidget")
        self.FinishLoyaltyWidget.setGeometry(QRect(0, 260, 451, 611))
        self.FinishLoyaltyAddToList = QPushButton(self.tab_11)
        self.FinishLoyaltyAddToList.setObjectName(u"FinishLoyaltyAddToList")
        self.FinishLoyaltyAddToList.setGeometry(QRect(10, 230, 121, 24))
        self.TraderFinishcomboBox = QComboBox(self.tab_11)
        self.TraderFinishcomboBox.setObjectName(u"TraderFinishcomboBox")
        self.TraderFinishcomboBox.setGeometry(QRect(10, 20, 121, 22))
        self.FinishLoyaltyObjective = QTextEdit(self.tab_11)
        self.FinishLoyaltyObjective.setObjectName(u"FinishLoyaltyObjective")
        self.FinishLoyaltyObjective.setGeometry(QRect(0, 60, 451, 161))
        self.tabWidget_5.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.FinishSkillRemoveFromList = QPushButton(self.tab_12)
        self.FinishSkillRemoveFromList.setObjectName(u"FinishSkillRemoveFromList")
        self.FinishSkillRemoveFromList.setGeometry(QRect(320, 230, 121, 24))
        self.FinishSkillValue = QLineEdit(self.tab_12)
        self.FinishSkillValue.setObjectName(u"FinishSkillValue")
        self.FinishSkillValue.setGeometry(QRect(140, 20, 71, 21))
        self.FinishSkillValue.setClearButtonEnabled(True)
        self.FinishDynamicLocaleSkill = QCheckBox(self.tab_12)
        self.FinishDynamicLocaleSkill.setObjectName(u"FinishDynamicLocaleSkill")
        self.FinishDynamicLocaleSkill.setGeometry(QRect(220, 20, 111, 20))
        self.label_2 = QLabel(self.tab_12)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 0, 49, 16))
        self.FinishSkillCompare = QComboBox(self.tab_12)
        self.FinishSkillCompare.setObjectName(u"FinishSkillCompare")
        self.FinishSkillCompare.setGeometry(QRect(330, 20, 121, 22))
        self.FinishSkillAddToList = QPushButton(self.tab_12)
        self.FinishSkillAddToList.setObjectName(u"FinishSkillAddToList")
        self.FinishSkillAddToList.setGeometry(QRect(10, 230, 121, 24))
        self.FinishSkillComboBox = QComboBox(self.tab_12)
        self.FinishSkillComboBox.setObjectName(u"FinishSkillComboBox")
        self.FinishSkillComboBox.setGeometry(QRect(10, 20, 121, 22))
        self.FinishSkillWidget = QListWidget(self.tab_12)
        self.FinishSkillWidget.setObjectName(u"FinishSkillWidget")
        self.FinishSkillWidget.setGeometry(QRect(0, 260, 451, 471))
        self.FinishSkillObjective = QTextEdit(self.tab_12)
        self.FinishSkillObjective.setObjectName(u"FinishSkillObjective")
        self.FinishSkillObjective.setGeometry(QRect(0, 60, 451, 161))
        self.tabWidget_5.addTab(self.tab_12, "")
        self.tab_18 = QWidget()
        self.tab_18.setObjectName(u"tab_18")
        self.FinishItemAmount = QLineEdit(self.tab_18)
        self.FinishItemAmount.setObjectName(u"FinishItemAmount")
        self.FinishItemAmount.setGeometry(QRect(170, 20, 51, 21))
        self.FinishItemAmount.setClearButtonEnabled(True)
        self.FinishItemEncoded = QCheckBox(self.tab_18)
        self.FinishItemEncoded.setObjectName(u"FinishItemEncoded")
        self.FinishItemEncoded.setGeometry(QRect(240, 50, 111, 20))
        self.FinishItemRemoveFromList = QPushButton(self.tab_18)
        self.FinishItemRemoveFromList.setObjectName(u"FinishItemRemoveFromList")
        self.FinishItemRemoveFromList.setGeometry(QRect(320, 180, 121, 24))
        self.FinishItemMaxDura = QLineEdit(self.tab_18)
        self.FinishItemMaxDura.setObjectName(u"FinishItemMaxDura")
        self.FinishItemMaxDura.setGeometry(QRect(170, 60, 51, 21))
        self.FinishItemMaxDura.setClearButtonEnabled(True)
        self.FinishItemDynamicLocale = QCheckBox(self.tab_18)
        self.FinishItemDynamicLocale.setObjectName(u"FinishItemDynamicLocale")
        self.FinishItemDynamicLocale.setGeometry(QRect(240, 20, 111, 20))
        self.label_23 = QLabel(self.tab_18)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 40, 81, 16))
        self.label_24 = QLabel(self.tab_18)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(80, 40, 81, 21))
        self.label_13 = QLabel(self.tab_18)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 0, 101, 16))
        self.label_25 = QLabel(self.tab_18)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 40, 81, 21))
        self.FinishItemMinDura = QLineEdit(self.tab_18)
        self.FinishItemMinDura.setObjectName(u"FinishItemMinDura")
        self.FinishItemMinDura.setGeometry(QRect(90, 60, 51, 21))
        self.FinishItemMinDura.setClearButtonEnabled(True)
        self.FinishItemAddToList = QPushButton(self.tab_18)
        self.FinishItemAddToList.setObjectName(u"FinishItemAddToList")
        self.FinishItemAddToList.setGeometry(QRect(10, 180, 121, 24))
        self.FinishItemWidget = QListWidget(self.tab_18)
        self.FinishItemWidget.setObjectName(u"FinishItemWidget")
        self.FinishItemWidget.setGeometry(QRect(0, 210, 451, 161))
        self.FinishItemId = QLineEdit(self.tab_18)
        self.FinishItemId.setObjectName(u"FinishItemId")
        self.FinishItemId.setGeometry(QRect(0, 20, 161, 21))
        self.FinishItemId.setClearButtonEnabled(True)
        self.FinishItemDogTag = QLineEdit(self.tab_18)
        self.FinishItemDogTag.setObjectName(u"FinishItemDogTag")
        self.FinishItemDogTag.setGeometry(QRect(0, 60, 61, 21))
        self.FinishItemDogTag.setClearButtonEnabled(True)
        self.FinishItemFIR = QCheckBox(self.tab_18)
        self.FinishItemFIR.setObjectName(u"FinishItemFIR")
        self.FinishItemFIR.setGeometry(QRect(350, 20, 111, 21))
        self.FinishFindObjective = QTextEdit(self.tab_18)
        self.FinishFindObjective.setObjectName(u"FinishFindObjective")
        self.FinishFindObjective.setGeometry(QRect(0, 90, 451, 81))
        self.FinishHandoverObjective = QTextEdit(self.tab_18)
        self.FinishHandoverObjective.setObjectName(u"FinishHandoverObjective")
        self.FinishHandoverObjective.setGeometry(QRect(0, 400, 451, 81))
        self.FinishHandoverWidget = QListWidget(self.tab_18)
        self.FinishHandoverWidget.setObjectName(u"FinishHandoverWidget")
        self.FinishHandoverWidget.setGeometry(QRect(0, 540, 451, 181))
        self.FinishHandoverRemoveList = QPushButton(self.tab_18)
        self.FinishHandoverRemoveList.setObjectName(u"FinishHandoverRemoveList")
        self.FinishHandoverRemoveList.setGeometry(QRect(320, 500, 121, 24))
        self.HandoverItemAddToList = QPushButton(self.tab_18)
        self.HandoverItemAddToList.setObjectName(u"HandoverItemAddToList")
        self.HandoverItemAddToList.setGeometry(QRect(10, 500, 121, 24))
        self.label_28 = QLabel(self.tab_18)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 380, 251, 16))
        self.tabWidget_5.addTab(self.tab_18, "")
        self.tab_19 = QWidget()
        self.tab_19.setObjectName(u"tab_19")
        self.label_31 = QLabel(self.tab_19)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(0, 10, 101, 16))
        self.ZoneOneSessionOnly = QCheckBox(self.tab_19)
        self.ZoneOneSessionOnly.setObjectName(u"ZoneOneSessionOnly")
        self.ZoneOneSessionOnly.setGeometry(QRect(70, 10, 121, 20))
        self.ZoneDoNotReset = QCheckBox(self.tab_19)
        self.ZoneDoNotReset.setObjectName(u"ZoneDoNotReset")
        self.ZoneDoNotReset.setGeometry(QRect(210, 10, 201, 20))
        self.ZoneRemoveFromList = QPushButton(self.tab_19)
        self.ZoneRemoveFromList.setObjectName(u"ZoneRemoveFromList")
        self.ZoneRemoveFromList.setGeometry(QRect(320, 160, 121, 24))
        self.ZoneVisitWidget = QListWidget(self.tab_19)
        self.ZoneVisitWidget.setObjectName(u"ZoneVisitWidget")
        self.ZoneVisitWidget.setGeometry(QRect(0, 190, 451, 241))
        self.ZoneAddToList = QPushButton(self.tab_19)
        self.ZoneAddToList.setObjectName(u"ZoneAddToList")
        self.ZoneAddToList.setGeometry(QRect(10, 160, 121, 24))
        self.FinishZoneName = QLineEdit(self.tab_19)
        self.FinishZoneName.setObjectName(u"FinishZoneName")
        self.FinishZoneName.setGeometry(QRect(0, 40, 171, 21))
        self.label_32 = QLabel(self.tab_19)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(180, 160, 91, 16))
        self.FinishVisitObjective = QTextEdit(self.tab_19)
        self.FinishVisitObjective.setObjectName(u"FinishVisitObjective")
        self.FinishVisitObjective.setGeometry(QRect(0, 70, 451, 81))
        self.tabWidget_5.addTab(self.tab_19, "")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_6 = QTabWidget(self.tab_5)
        self.tabWidget_6.setObjectName(u"tabWidget_6")
        self.tabWidget_6.setGeometry(QRect(0, 0, 542, 911))
        self.tab_14 = QWidget()
        self.tab_14.setObjectName(u"tab_14")
        self.FailQuestId = QLineEdit(self.tab_14)
        self.FailQuestId.setObjectName(u"FailQuestId")
        self.FailQuestId.setGeometry(QRect(10, 30, 121, 21))
        self.FailQuestId.setMaxLength(24)
        self.FailQuestId.setClearButtonEnabled(True)
        self.Label232 = QLabel(self.tab_14)
        self.Label232.setObjectName(u"Label232")
        self.Label232.setGeometry(QRect(10, 10, 49, 16))
        self.FailQuestStatus = QComboBox(self.tab_14)
        self.FailQuestStatus.setObjectName(u"FailQuestStatus")
        self.FailQuestStatus.setGeometry(QRect(140, 30, 121, 21))
        self.FailQuestStatus.setEditable(False)
        self.FailQuestStatus.setModelColumn(0)
        self.FailQuestDynamicLocale = QCheckBox(self.tab_14)
        self.FailQuestDynamicLocale.setObjectName(u"FailQuestDynamicLocale")
        self.FailQuestDynamicLocale.setGeometry(QRect(270, 30, 111, 20))
        self.FailQuestDynamicLocale.setChecked(False)
        self.FailQuestAddToList = QPushButton(self.tab_14)
        self.FailQuestAddToList.setObjectName(u"FailQuestAddToList")
        self.FailQuestAddToList.setGeometry(QRect(10, 60, 121, 24))
        self.FailQuestRemoveFromList = QPushButton(self.tab_14)
        self.FailQuestRemoveFromList.setObjectName(u"FailQuestRemoveFromList")
        self.FailQuestRemoveFromList.setGeometry(QRect(140, 60, 121, 24))
        self.line_24 = QFrame(self.tab_14)
        self.line_24.setObjectName(u"line_24")
        self.line_24.setGeometry(QRect(-10, 260, 471, 20))
        self.line_24.setFrameShape(QFrame.HLine)
        self.line_24.setFrameShadow(QFrame.Sunken)
        self.FailQuestWidget = QListWidget(self.tab_14)
        self.FailQuestWidget.setObjectName(u"FailQuestWidget")
        self.FailQuestWidget.setGeometry(QRect(0, 90, 451, 171))
        self.FailStandingCompare = QComboBox(self.tab_14)
        self.FailStandingCompare.setObjectName(u"FailStandingCompare")
        self.FailStandingCompare.setGeometry(QRect(190, 290, 121, 21))
        self.FailStandingCompare.setEditable(False)
        self.FailStandingCompare.setModelColumn(0)
        self.line_25 = QFrame(self.tab_14)
        self.line_25.setObjectName(u"line_25")
        self.line_25.setGeometry(QRect(-10, 520, 471, 20))
        self.line_25.setFrameShape(QFrame.HLine)
        self.line_25.setFrameShadow(QFrame.Sunken)
        self.Label232_2 = QLabel(self.tab_14)
        self.Label232_2.setObjectName(u"Label232_2")
        self.Label232_2.setGeometry(QRect(10, 270, 49, 16))
        self.FailStandingWidget = QListWidget(self.tab_14)
        self.FailStandingWidget.setObjectName(u"FailStandingWidget")
        self.FailStandingWidget.setGeometry(QRect(0, 350, 451, 171))
        self.FailStandingRemoveFromList = QPushButton(self.tab_14)
        self.FailStandingRemoveFromList.setObjectName(u"FailStandingRemoveFromList")
        self.FailStandingRemoveFromList.setGeometry(QRect(140, 320, 121, 24))
        self.FailStandingAddToList = QPushButton(self.tab_14)
        self.FailStandingAddToList.setObjectName(u"FailStandingAddToList")
        self.FailStandingAddToList.setGeometry(QRect(10, 320, 121, 24))
        self.FailStandingDynamicLocale = QCheckBox(self.tab_14)
        self.FailStandingDynamicLocale.setObjectName(u"FailStandingDynamicLocale")
        self.FailStandingDynamicLocale.setGeometry(QRect(330, 290, 111, 20))
        self.FailStandingDynamicLocale.setChecked(False)
        self.FailStandingTrader = QComboBox(self.tab_14)
        self.FailStandingTrader.setObjectName(u"FailStandingTrader")
        self.FailStandingTrader.setGeometry(QRect(10, 290, 121, 21))
        self.FailStandingTrader.setEditable(False)
        self.FailStandingTrader.setModelColumn(0)
        self.FailStandingValue = QLineEdit(self.tab_14)
        self.FailStandingValue.setObjectName(u"FailStandingValue")
        self.FailStandingValue.setGeometry(QRect(140, 290, 41, 21))
        self.FailStandingValue.setMaxLength(24)
        self.FailStandingValue.setClearButtonEnabled(True)
        self.tabWidget_6.addTab(self.tab_14, "")
        self.tab_15 = QWidget()
        self.tab_15.setObjectName(u"tab_15")
        self.FailExitStatusStatus = QComboBox(self.tab_15)
        self.FailExitStatusStatus.setObjectName(u"FailExitStatusStatus")
        self.FailExitStatusStatus.setGeometry(QRect(10, 20, 191, 21))
        self.FailExitStatusWidget = QListWidget(self.tab_15)
        self.FailExitStatusWidget.setObjectName(u"FailExitStatusWidget")
        self.FailExitStatusWidget.setGeometry(QRect(10, 80, 191, 151))
        self.FailExitStatusAdd = QPushButton(self.tab_15)
        self.FailExitStatusAdd.setObjectName(u"FailExitStatusAdd")
        self.FailExitStatusAdd.setGeometry(QRect(10, 50, 81, 24))
        self.FailExitStatusRemove = QPushButton(self.tab_15)
        self.FailExitStatusRemove.setObjectName(u"FailExitStatusRemove")
        self.FailExitStatusRemove.setGeometry(QRect(120, 50, 81, 24))
        self.FailExitDynamicLocale = QCheckBox(self.tab_15)
        self.FailExitDynamicLocale.setObjectName(u"FailExitDynamicLocale")
        self.FailExitDynamicLocale.setGeometry(QRect(220, 240, 111, 20))
        self.FailExitDynamicLocale.setChecked(False)
        self.FailExitOneSession = QCheckBox(self.tab_15)
        self.FailExitOneSession.setObjectName(u"FailExitOneSession")
        self.FailExitOneSession.setGeometry(QRect(340, 240, 111, 20))
        self.FailExitOneSession.setChecked(False)
        self.FailExitDoNotReset = QCheckBox(self.tab_15)
        self.FailExitDoNotReset.setObjectName(u"FailExitDoNotReset")
        self.FailExitDoNotReset.setGeometry(QRect(10, 240, 191, 20))
        self.FailExitDoNotReset.setChecked(False)
        self.label_16 = QLabel(self.tab_15)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 0, 61, 16))
        self.FailExitWidget = QListWidget(self.tab_15)
        self.FailExitWidget.setObjectName(u"FailExitWidget")
        self.FailExitWidget.setGeometry(QRect(0, 300, 451, 171))
        self.line_23 = QFrame(self.tab_15)
        self.line_23.setObjectName(u"line_23")
        self.line_23.setGeometry(QRect(-10, 470, 471, 20))
        self.line_23.setFrameShape(QFrame.HLine)
        self.line_23.setFrameShadow(QFrame.Sunken)
        self.FailExitAddToList = QPushButton(self.tab_15)
        self.FailExitAddToList.setObjectName(u"FailExitAddToList")
        self.FailExitAddToList.setGeometry(QRect(10, 270, 75, 24))
        self.FailExitRemoveFromList = QPushButton(self.tab_15)
        self.FailExitRemoveFromList.setObjectName(u"FailExitRemoveFromList")
        self.FailExitRemoveFromList.setGeometry(QRect(100, 270, 111, 24))
        self.FailLocationAdd = QPushButton(self.tab_15)
        self.FailLocationAdd.setObjectName(u"FailLocationAdd")
        self.FailLocationAdd.setGeometry(QRect(250, 50, 81, 24))
        self.FailExitLocationWidget = QListWidget(self.tab_15)
        self.FailExitLocationWidget.setObjectName(u"FailExitLocationWidget")
        self.FailExitLocationWidget.setGeometry(QRect(250, 80, 191, 151))
        self.FailLocationRemove = QPushButton(self.tab_15)
        self.FailLocationRemove.setObjectName(u"FailLocationRemove")
        self.FailLocationRemove.setGeometry(QRect(360, 50, 81, 24))
        self.FailExitStatusLocation = QComboBox(self.tab_15)
        self.FailExitStatusLocation.setObjectName(u"FailExitStatusLocation")
        self.FailExitStatusLocation.setGeometry(QRect(250, 20, 191, 21))
        self.tabWidget_6.addTab(self.tab_15, "")
        self.tab_16 = QWidget()
        self.tab_16.setObjectName(u"tab_16")
        self.tabWidget_6.addTab(self.tab_16, "")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget_3 = QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 461, 981))
        self.tabWidget_3.setTabShape(QTabWidget.Rounded)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_9 = QLabel(self.tab_7)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(9, 9, 57, 16))
        self.StartedAddItemToList = QPushButton(self.tab_7)
        self.StartedAddItemToList.setObjectName(u"StartedAddItemToList")
        self.StartedAddItemToList.setGeometry(QRect(330, 30, 111, 24))
        self.StartedItemId = QLineEdit(self.tab_7)
        self.StartedItemId.setObjectName(u"StartedItemId")
        self.StartedItemId.setGeometry(QRect(10, 30, 132, 21))
        self.StartedItemId.setMaxLength(24)
        self.StartedItemId.setClearButtonEnabled(True)
        self.StartedItemAmount = QLineEdit(self.tab_7)
        self.StartedItemAmount.setObjectName(u"StartedItemAmount")
        self.StartedItemAmount.setGeometry(QRect(170, 30, 132, 21))
        self.StartedItemAmount.setMaxLength(24)
        self.StartedItemAmount.setClearButtonEnabled(True)
        self.StartedItemWidget = QListWidget(self.tab_7)
        self.StartedItemWidget.setObjectName(u"StartedItemWidget")
        self.StartedItemWidget.setGeometry(QRect(0, 110, 451, 192))
        self.StartedRemoveItemFromList = QPushButton(self.tab_7)
        self.StartedRemoveItemFromList.setObjectName(u"StartedRemoveItemFromList")
        self.StartedRemoveItemFromList.setGeometry(QRect(330, 60, 111, 24))
        self.line_9 = QFrame(self.tab_7)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 300, 461, 20))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.StartedAssortTraderUnlockRemoveFromList = QPushButton(self.tab_7)
        self.StartedAssortTraderUnlockRemoveFromList.setObjectName(u"StartedAssortTraderUnlockRemoveFromList")
        self.StartedAssortTraderUnlockRemoveFromList.setGeometry(QRect(320, 360, 121, 24))
        self.StartedAssortTraderComboBox = QComboBox(self.tab_7)
        self.StartedAssortTraderComboBox.setObjectName(u"StartedAssortTraderComboBox")
        self.StartedAssortTraderComboBox.setGeometry(QRect(0, 330, 131, 21))
        self.StartedAssortTraderComboBox.setEditable(False)
        self.StartedAssortTraderComboBox.setModelColumn(0)
        self.line_21 = QFrame(self.tab_7)
        self.line_21.setObjectName(u"line_21")
        self.line_21.setGeometry(QRect(0, 600, 451, 16))
        self.line_21.setFrameShape(QFrame.HLine)
        self.line_21.setFrameShadow(QFrame.Sunken)
        self.StartedAssortTraderItemId = QLineEdit(self.tab_7)
        self.StartedAssortTraderItemId.setObjectName(u"StartedAssortTraderItemId")
        self.StartedAssortTraderItemId.setGeometry(QRect(160, 330, 132, 21))
        self.StartedAssortTraderItemId.setMaxLength(24)
        self.StartedAssortTraderItemId.setClearButtonEnabled(True)
        self.StartedAssortTraderUnlockAddToList = QPushButton(self.tab_7)
        self.StartedAssortTraderUnlockAddToList.setObjectName(u"StartedAssortTraderUnlockAddToList")
        self.StartedAssortTraderUnlockAddToList.setGeometry(QRect(320, 330, 121, 24))
        self.label_20 = QLabel(self.tab_7)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 390, 111, 16))
        self.label_21 = QLabel(self.tab_7)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 310, 84, 16))
        self.StartedAssortLoyaltyLevelComboBox = QComboBox(self.tab_7)
        self.StartedAssortLoyaltyLevelComboBox.setObjectName(u"StartedAssortLoyaltyLevelComboBox")
        self.StartedAssortLoyaltyLevelComboBox.setGeometry(QRect(0, 360, 131, 21))
        self.StartedAssortLoyaltyLevelComboBox.setEditable(False)
        self.StartedAssortLoyaltyLevelComboBox.setModelColumn(0)
        self.StartedAssortTraderWidget = QListWidget(self.tab_7)
        self.StartedAssortTraderWidget.setObjectName(u"StartedAssortTraderWidget")
        self.StartedAssortTraderWidget.setGeometry(QRect(0, 410, 451, 191))
        self.line_22 = QFrame(self.tab_7)
        self.line_22.setObjectName(u"line_22")
        self.line_22.setGeometry(QRect(0, 380, 451, 16))
        self.line_22.setFrameShape(QFrame.HLine)
        self.line_22.setFrameShadow(QFrame.Sunken)
        self.label_22 = QLabel(self.tab_7)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 90, 111, 16))
        self.line_26 = QFrame(self.tab_7)
        self.line_26.setObjectName(u"line_26")
        self.line_26.setGeometry(QRect(10, 80, 437, 16))
        self.line_26.setFrameShape(QFrame.HLine)
        self.line_26.setFrameShadow(QFrame.Sunken)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.ExperienceAmount = QLineEdit(self.tab_8)
        self.ExperienceAmount.setObjectName(u"ExperienceAmount")
        self.ExperienceAmount.setGeometry(QRect(9, 9, 132, 21))
        self.ExperienceAmount.setMaxLength(24)
        self.ExperienceAmount.setClearButtonEnabled(True)
        self.CurrencyAmount = QLineEdit(self.tab_8)
        self.CurrencyAmount.setObjectName(u"CurrencyAmount")
        self.CurrencyAmount.setGeometry(QRect(170, 60, 132, 21))
        self.CurrencyAmount.setMaxLength(24)
        self.CurrencyAmount.setClearButtonEnabled(True)
        self.CurrencyType = QComboBox(self.tab_8)
        self.CurrencyType.setObjectName(u"CurrencyType")
        self.CurrencyType.setGeometry(QRect(10, 60, 131, 21))
        self.CurrencyType.setEditable(False)
        self.CurrencyType.setModelColumn(0)
        self.line_5 = QFrame(self.tab_8)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(9, 260, 437, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.tab_8)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(9, 270, 84, 16))
        self.label_7 = QLabel(self.tab_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(9, 350, 111, 16))
        self.line_6 = QFrame(self.tab_8)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(9, 340, 437, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.tab_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(9, 500, 72, 16))
        self.StandingAmount = QLineEdit(self.tab_8)
        self.StandingAmount.setObjectName(u"StandingAmount")
        self.StandingAmount.setGeometry(QRect(170, 290, 132, 21))
        self.StandingAmount.setMaxLength(24)
        self.StandingAmount.setClearButtonEnabled(True)
        self.line_7 = QFrame(self.tab_8)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(9, 570, 437, 16))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.SuccessAddStandingToList = QPushButton(self.tab_8)
        self.SuccessAddStandingToList.setObjectName(u"SuccessAddStandingToList")
        self.SuccessAddStandingToList.setGeometry(QRect(330, 290, 121, 24))
        self.SuccessRewardId = QLineEdit(self.tab_8)
        self.SuccessRewardId.setObjectName(u"SuccessRewardId")
        self.SuccessRewardId.setGeometry(QRect(9, 520, 132, 21))
        self.SuccessRewardId.setMaxLength(24)
        self.SuccessRewardId.setClearButtonEnabled(True)
        self.SuccessRewardAmount = QLineEdit(self.tab_8)
        self.SuccessRewardAmount.setObjectName(u"SuccessRewardAmount")
        self.SuccessRewardAmount.setGeometry(QRect(162, 540, 132, 21))
        self.SuccessRewardAmount.setMaxLength(24)
        self.SuccessRewardAmount.setClearButtonEnabled(True)
        self.SuccessAddItemToList = QPushButton(self.tab_8)
        self.SuccessAddItemToList.setObjectName(u"SuccessAddItemToList")
        self.SuccessAddItemToList.setGeometry(QRect(320, 520, 131, 24))
        self.line_8 = QFrame(self.tab_8)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(9, 490, 437, 16))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(self.tab_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(9, 580, 88, 16))
        self.SuccessAddCurrencyToList = QPushButton(self.tab_8)
        self.SuccessAddCurrencyToList.setObjectName(u"SuccessAddCurrencyToList")
        self.SuccessAddCurrencyToList.setGeometry(QRect(330, 60, 121, 24))
        self.line_12 = QFrame(self.tab_8)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(10, 30, 437, 16))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.tab_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 40, 84, 16))
        self.line_13 = QFrame(self.tab_8)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(10, 110, 437, 16))
        self.line_13.setFrameShape(QFrame.HLine)
        self.line_13.setFrameShadow(QFrame.Sunken)
        self.label_12 = QLabel(self.tab_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 120, 111, 16))
        self.SuccessCurrencyWidget = QListWidget(self.tab_8)
        self.SuccessCurrencyWidget.setObjectName(u"SuccessCurrencyWidget")
        self.SuccessCurrencyWidget.setGeometry(QRect(0, 140, 451, 111))
        self.SuccessCurrencyRemoveFromList = QPushButton(self.tab_8)
        self.SuccessCurrencyRemoveFromList.setObjectName(u"SuccessCurrencyRemoveFromList")
        self.SuccessCurrencyRemoveFromList.setGeometry(QRect(330, 90, 121, 24))
        self.SuccessRemoveStandingFromList = QPushButton(self.tab_8)
        self.SuccessRemoveStandingFromList.setObjectName(u"SuccessRemoveStandingFromList")
        self.SuccessRemoveStandingFromList.setGeometry(QRect(330, 320, 121, 24))
        self.SuccessRemoveItemFromList = QPushButton(self.tab_8)
        self.SuccessRemoveItemFromList.setObjectName(u"SuccessRemoveItemFromList")
        self.SuccessRemoveItemFromList.setGeometry(QRect(320, 550, 131, 24))
        self.SuccessStandingWidget = QListWidget(self.tab_8)
        self.SuccessStandingWidget.setObjectName(u"SuccessStandingWidget")
        self.SuccessStandingWidget.setGeometry(QRect(0, 370, 451, 111))
        self.SuccessItemWidget = QListWidget(self.tab_8)
        self.SuccessItemWidget.setObjectName(u"SuccessItemWidget")
        self.SuccessItemWidget.setGeometry(QRect(0, 600, 451, 111))
        self.line_15 = QFrame(self.tab_8)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(10, 750, 437, 16))
        self.line_15.setFrameShape(QFrame.HLine)
        self.line_15.setFrameShadow(QFrame.Sunken)
        self.SuccessTrader = QComboBox(self.tab_8)
        self.SuccessTrader.setObjectName(u"SuccessTrader")
        self.SuccessTrader.setGeometry(QRect(20, 290, 131, 21))
        self.SuccessTrader.setEditable(False)
        self.SuccessTrader.setModelColumn(0)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_13 = QWidget()
        self.tab_13.setObjectName(u"tab_13")
        self.AssortTraderItemId = QLineEdit(self.tab_13)
        self.AssortTraderItemId.setObjectName(u"AssortTraderItemId")
        self.AssortTraderItemId.setGeometry(QRect(160, 20, 132, 21))
        self.AssortTraderItemId.setMaxLength(24)
        self.AssortTraderItemId.setClearButtonEnabled(True)
        self.AssortTraderUnlockRemoveFromList = QPushButton(self.tab_13)
        self.AssortTraderUnlockRemoveFromList.setObjectName(u"AssortTraderUnlockRemoveFromList")
        self.AssortTraderUnlockRemoveFromList.setGeometry(QRect(320, 50, 121, 24))
        self.AssortTraderComboBox = QComboBox(self.tab_13)
        self.AssortTraderComboBox.setObjectName(u"AssortTraderComboBox")
        self.AssortTraderComboBox.setGeometry(QRect(0, 20, 131, 21))
        self.AssortTraderComboBox.setEditable(False)
        self.AssortTraderComboBox.setModelColumn(0)
        self.AssortTraderUnlockAddToList = QPushButton(self.tab_13)
        self.AssortTraderUnlockAddToList.setObjectName(u"AssortTraderUnlockAddToList")
        self.AssortTraderUnlockAddToList.setGeometry(QRect(320, 20, 121, 24))
        self.label_14 = QLabel(self.tab_13)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 80, 111, 16))
        self.AssortTraderAssortUnlockWidget = QListWidget(self.tab_13)
        self.AssortTraderAssortUnlockWidget.setObjectName(u"AssortTraderAssortUnlockWidget")
        self.AssortTraderAssortUnlockWidget.setGeometry(QRect(0, 100, 451, 131))
        self.line_17 = QFrame(self.tab_13)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 70, 437, 16))
        self.line_17.setFrameShape(QFrame.HLine)
        self.line_17.setFrameShadow(QFrame.Sunken)
        self.label_15 = QLabel(self.tab_13)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 84, 16))
        self.line_18 = QFrame(self.tab_13)
        self.line_18.setObjectName(u"line_18")
        self.line_18.setGeometry(QRect(0, 230, 437, 16))
        self.line_18.setFrameShape(QFrame.HLine)
        self.line_18.setFrameShadow(QFrame.Sunken)
        self.AssortLoyaltyLevelComboBox = QComboBox(self.tab_13)
        self.AssortLoyaltyLevelComboBox.setObjectName(u"AssortLoyaltyLevelComboBox")
        self.AssortLoyaltyLevelComboBox.setGeometry(QRect(0, 50, 131, 21))
        self.AssortLoyaltyLevelComboBox.setEditable(False)
        self.AssortLoyaltyLevelComboBox.setModelColumn(0)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.CanShowNotifications = QCheckBox(self.QuestCreator)
        self.CanShowNotifications.setObjectName(u"CanShowNotifications")
        self.CanShowNotifications.setGeometry(QRect(620, 0, 146, 20))
        self.CanShowNotifications.setChecked(True)
        self.InstantComplete = QCheckBox(self.QuestCreator)
        self.InstantComplete.setObjectName(u"InstantComplete")
        self.InstantComplete.setGeometry(QRect(770, 60, 114, 20))
        self.InstantComplete.setChecked(False)
        self.Note = QTextEdit(self.QuestCreator)
        self.Note.setObjectName(u"Note")
        self.Note.setGeometry(QRect(350, 540, 441, 201))
        self.Side = QComboBox(self.QuestCreator)
        self.Side.setObjectName(u"Side")
        self.Side.setGeometry(QRect(900, 60, 141, 21))
        self.Side.setEditable(False)
        self.Side.setModelColumn(0)
        self.QuestName = QLineEdit(self.QuestCreator)
        self.QuestName.setObjectName(u"QuestName")
        self.QuestName.setGeometry(QRect(350, 30, 251, 21))
        self.QuestName.setClearButtonEnabled(True)
        self._Id = QLineEdit(self.QuestCreator)
        self._Id.setObjectName(u"_Id")
        self._Id.setGeometry(QRect(350, 0, 251, 21))
        self._Id.setMaxLength(24)
        self._Id.setClearButtonEnabled(True)
        self.DynamicLocale = QCheckBox(self.QuestCreator)
        self.DynamicLocale.setObjectName(u"DynamicLocale")
        self.DynamicLocale.setGeometry(QRect(620, 30, 111, 21))
        self.DynamicLocale.setChecked(False)
        self.SuccessMessage = QTextEdit(self.QuestCreator)
        self.SuccessMessage.setObjectName(u"SuccessMessage")
        self.SuccessMessage.setGeometry(QRect(810, 100, 441, 201))
        self.ImagePath = QLineEdit(self.QuestCreator)
        self.ImagePath.setObjectName(u"ImagePath")
        self.ImagePath.setGeometry(QRect(350, 60, 251, 21))
        self.ImagePath.setMaxLength(512)
        self.ImagePath.setClearButtonEnabled(True)
        self.RequiresKey = QCheckBox(self.QuestCreator)
        self.RequiresKey.setObjectName(u"RequiresKey")
        self.RequiresKey.setGeometry(QRect(770, 0, 100, 20))
        self.Restartable = QCheckBox(self.QuestCreator)
        self.Restartable.setObjectName(u"Restartable")
        self.Restartable.setGeometry(QRect(620, 60, 82, 20))
        self.Restartable.setChecked(False)
        self.LoadQuestFile = QPushButton(self.QuestCreator)
        self.LoadQuestFile.setObjectName(u"LoadQuestFile")
        self.LoadQuestFile.setGeometry(QRect(120, 10, 91, 24))
        self.line_10 = QFrame(self.QuestCreator)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(330, 0, 20, 791))
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.QuestCreator)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(1250, -20, 20, 811))
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.TradercomboBox = QComboBox(self.QuestCreator)
        self.TradercomboBox.setObjectName(u"TradercomboBox")
        self.TradercomboBox.setGeometry(QRect(900, 0, 141, 22))
        self.LocationComboBox = QComboBox(self.QuestCreator)
        self.LocationComboBox.setObjectName(u"LocationComboBox")
        self.LocationComboBox.setGeometry(QRect(900, 30, 141, 22))
        self.TraderIdTextField = QLineEdit(self.QuestCreator)
        self.TraderIdTextField.setObjectName(u"TraderIdTextField")
        self.TraderIdTextField.setGeometry(QRect(1050, 0, 201, 21))
        self.TraderIdTextField.setMaxLength(24)
        self.TraderIdTextField.setClearButtonEnabled(True)
        self.LocationIdTextField = QLineEdit(self.QuestCreator)
        self.LocationIdTextField.setObjectName(u"LocationIdTextField")
        self.LocationIdTextField.setGeometry(QRect(1050, 30, 201, 21))
        self.LocationIdTextField.setMaxLength(24)
        self.LocationIdTextField.setClearButtonEnabled(True)
        self.line_3 = QFrame(self.QuestCreator)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(337, 80, 921, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.QuestFileWidget = QListWidget(self.QuestCreator)
        self.QuestFileWidget.setObjectName(u"QuestFileWidget")
        self.QuestFileWidget.setGeometry(QRect(10, 220, 321, 301))
        self.RemoveFromQuestFile = QPushButton(self.QuestCreator)
        self.RemoveFromQuestFile.setObjectName(u"RemoveFromQuestFile")
        self.RemoveFromQuestFile.setGeometry(QRect(230, 50, 101, 24))
        self.EditQuest = QPushButton(self.QuestCreator)
        self.EditQuest.setObjectName(u"EditQuest")
        self.EditQuest.setGeometry(QRect(0, 50, 101, 24))
        self.SaveQuestFile = QPushButton(self.QuestCreator)
        self.SaveQuestFile.setObjectName(u"SaveQuestFile")
        self.SaveQuestFile.setGeometry(QRect(230, 10, 101, 24))
        self.NewQuestFile = QPushButton(self.QuestCreator)
        self.NewQuestFile.setObjectName(u"NewQuestFile")
        self.NewQuestFile.setGeometry(QRect(0, 10, 101, 24))
        self.LoadFilePath = QLineEdit(self.QuestCreator)
        self.LoadFilePath.setObjectName(u"LoadFilePath")
        self.LoadFilePath.setGeometry(QRect(0, 180, 331, 21))
        self.LoadFilePath.setReadOnly(True)
        self.LoadFilePath.setClearButtonEnabled(False)
        self.label_17 = QLabel(self.QuestCreator)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 160, 71, 16))
        self.LoadedLocalePath = QLineEdit(self.QuestCreator)
        self.LoadedLocalePath.setObjectName(u"LoadedLocalePath")
        self.LoadedLocalePath.setGeometry(QRect(0, 140, 331, 21))
        self.LoadedLocalePath.setReadOnly(True)
        self.LoadedLocalePath.setClearButtonEnabled(False)
        self.label_18 = QLabel(self.QuestCreator)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 120, 101, 16))
        self.Author = QLabel(self.QuestCreator)
        self.Author.setObjectName(u"Author")
        self.Author.setGeometry(QRect(350, 790, 171, 31))
        self.Author.setWordWrap(False)
        self.GithubPath = QLineEdit(self.QuestCreator)
        self.GithubPath.setObjectName(u"GithubPath")
        self.GithubPath.setGeometry(QRect(530, 790, 231, 31))
        self.GithubPath.setMaxLength(512)
        self.GithubPath.setReadOnly(True)
        self.GithubPath.setClearButtonEnabled(False)
        self.ALPHAVERSION = QLabel(self.QuestCreator)
        self.ALPHAVERSION.setObjectName(u"ALPHAVERSION")
        self.ALPHAVERSION.setGeometry(QRect(840, 790, 421, 31))
        self.ALPHAVERSION.setWordWrap(False)
        self.line_20 = QFrame(self.QuestCreator)
        self.line_20.setObjectName(u"line_20")
        self.line_20.setGeometry(QRect(340, 780, 921, 20))
        self.line_20.setFrameShape(QFrame.HLine)
        self.line_20.setFrameShadow(QFrame.Sunken)
        self.ClearButton = QPushButton(self.QuestCreator)
        self.ClearButton.setObjectName(u"ClearButton")
        self.ClearButton.setGeometry(QRect(350, 760, 101, 24))
        self.Author_2 = QLabel(self.QuestCreator)
        self.Author_2.setObjectName(u"Author_2")
        self.Author_2.setGeometry(QRect(460, 750, 221, 41))
        self.Author_2.setWordWrap(False)
        self.CurrentQuestText = QLineEdit(self.QuestCreator)
        self.CurrentQuestText.setObjectName(u"CurrentQuestText")
        self.CurrentQuestText.setGeometry(QRect(0, 100, 331, 21))
        self.CurrentQuestText.setReadOnly(True)
        self.CurrentQuestText.setClearButtonEnabled(False)
        self.label_26 = QLabel(self.QuestCreator)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(0, 80, 101, 16))
        self.label_29 = QLabel(self.QuestCreator)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(120, 520, 81, 20))
        self.label_30 = QLabel(self.QuestCreator)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(120, 200, 91, 20))
        self.ClearConsole = QPushButton(self.QuestCreator)
        self.ClearConsole.setObjectName(u"ClearConsole")
        self.ClearConsole.setGeometry(QRect(110, 790, 101, 31))
        self.Console = QListWidget(self.QuestCreator)
        self.Console.setObjectName(u"Console")
        self.Console.setGeometry(QRect(10, 540, 321, 251))
        self.tabWidget.addTab(self.QuestCreator, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_19 = QLabel(self.tab_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(780, 370, 329, 58))
        font = QFont()
        font.setPointSize(32)
        self.label_19.setFont(font)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_17 = QWidget()
        self.tab_17.setObjectName(u"tab_17")
        self.label_27 = QLabel(self.tab_17)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(780, 370, 329, 58))
        self.label_27.setFont(font)
        self.tabWidget.addTab(self.tab_17, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1755, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(1)
        self.tabWidget_6.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tarkov Tools", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open(TODO)", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save(TODO)", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As(TODO)", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings(TODO)", None))
        self.actionThese_Do_Nothing.setText(QCoreApplication.translate("MainWindow", u"These Do Nothing fool!", None))
        self.FailMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fail Message", None))
        self.ChangeMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Change Message", None))
        self.SecretQuest.setText(QCoreApplication.translate("MainWindow", u"Secret Quest", None))
        self.Description.setMarkdown("")
        self.Description.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Description.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Description (Same as Start and Accept messages)", None))
        self.Type.setCurrentText("")
        self.Type.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.AvailableForStartLevelRequirement.setInputMask("")
        self.AvailableForStartLevelRequirement.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.AvailableForStartLevelRequirement.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Level requirement", None))
        self.AvailableForStartLevelRequirementCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.AvailableForStartQuestId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest Id", None))
        self.AvailableForStartAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.AvailableForStartDynamicLocaleLevel.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.AvailableForStartDynamicLocaleQuest.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.AvailableForStartStatus.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Quest Requirement", None))
        self.AvailableForStartRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.AvailableForStartLoyaltyRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.AvailableForStartLoyaltyAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.AvailableForStartTraderComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.AvailableForStartLoyaltyDynamicLocaleQuest.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Trader Loyalty Requirements", None))
        self.AvailableCompareLoyaltyComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.AvailableForStartLoyaltyValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Loyalty value", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Available For Start", None))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Index", None))
        self.checkBox_10.setText(QCoreApplication.translate("MainWindow", u"Do Not Reset If Counter Completed", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Loyalty", None))
        self.FinishLoyaltyDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FinishLoyaltyValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.FinishLoyaltyCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.FinishLoyaltyRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove from List", None))
        self.FinishLoyaltyAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.TraderFinishcomboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.FinishLoyaltyObjective.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Objective Message", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Loyalty", None))
        self.FinishSkillRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove from List", None))
        self.FinishSkillValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.FinishDynamicLocaleSkill.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Skill", None))
        self.FinishSkillCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.FinishSkillAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishSkillComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Skill", None))
        self.FinishSkillObjective.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Objective Message", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Skill", None))
        self.FinishItemAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.FinishItemEncoded.setText(QCoreApplication.translate("MainWindow", u"IsEncoded", None))
        self.FinishItemRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove from List", None))
        self.FinishItemMaxDura.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.FinishItemMaxDura.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Max Dura", None))
        self.FinishItemDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Dog Tag Level", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Min Durability", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Find Items</p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Max Durability", None))
        self.FinishItemMinDura.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.FinishItemMinDura.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Min Dura", None))
        self.FinishItemAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ItemId", None))
        self.FinishItemDogTag.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.FinishItemDogTag.setPlaceholderText(QCoreApplication.translate("MainWindow", u"DogTag Lvl", None))
        self.FinishItemFIR.setText(QCoreApplication.translate("MainWindow", u"Found in raid", None))
        self.FinishFindObjective.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Find Objective Message", None))
        self.FinishHandoverObjective.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Handover Objective Message", None))
        self.FinishHandoverRemoveList.setText(QCoreApplication.translate("MainWindow", u"Remove from List", None))
        self.HandoverItemAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Handover: Uses the same props from above.", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_18), QCoreApplication.translate("MainWindow", u"Items", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Visit Place</p></body></html>", None))
        self.ZoneOneSessionOnly.setText(QCoreApplication.translate("MainWindow", u"One Session Only", None))
        self.ZoneDoNotReset.setText(QCoreApplication.translate("MainWindow", u"Do Not reset if counter completed", None))
        self.ZoneRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove from List", None))
        self.ZoneAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishZoneName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Zone Name", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>This is very WIP.</p></body></html>", None))
        self.FinishVisitObjective.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Visit Objective Message", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_19), QCoreApplication.translate("MainWindow", u"Visit Place", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Available For Finish", None))
        self.FailQuestId.setText("")
        self.FailQuestId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest Id", None))
        self.Label232.setText(QCoreApplication.translate("MainWindow", u"Quest", None))
        self.FailQuestStatus.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.FailQuestDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FailQuestAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FailQuestRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.FailStandingCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.Label232_2.setText(QCoreApplication.translate("MainWindow", u"Standing", None))
        self.FailStandingRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.FailStandingAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FailStandingDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FailStandingTrader.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.FailStandingValue.setText("")
        self.FailStandingValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_14), QCoreApplication.translate("MainWindow", u"Quest and Standing", None))
        self.FailExitStatusStatus.setCurrentText("")
        self.FailExitStatusStatus.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.FailExitStatusAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.FailExitStatusRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.FailExitDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FailExitOneSession.setText(QCoreApplication.translate("MainWindow", u"oneSessionOnly", None))
        self.FailExitDoNotReset.setText(QCoreApplication.translate("MainWindow", u"DoNotResetIfCounterCompleted", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Exit Status", None))
        self.FailExitAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FailExitRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.FailLocationAdd.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.FailLocationRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.FailExitStatusLocation.setCurrentText("")
        self.FailExitStatusLocation.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Location", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_15), QCoreApplication.translate("MainWindow", u"Exit Status", None))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.tab_16), QCoreApplication.translate("MainWindow", u"Kills", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Fail", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Start Items", None))
        self.StartedAddItemToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.StartedItemId.setText("")
        self.StartedItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Item Id", None))
        self.StartedItemAmount.setText("")
        self.StartedItemAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.StartedRemoveItemFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.StartedAssortTraderUnlockRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.StartedAssortTraderComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.StartedAssortTraderItemId.setText("")
        self.StartedAssortTraderItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ItemId", None))
        self.StartedAssortTraderUnlockAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Assort Reward List", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Assort Unlock", None))
        self.StartedAssortLoyaltyLevelComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Loyalty level", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Item Reward List", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Started", None))
        self.ExperienceAmount.setText("")
        self.ExperienceAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Experience Amount", None))
        self.CurrencyAmount.setText("")
        self.CurrencyAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Currency Amount", None))
        self.CurrencyType.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Currency Type", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Trader Standing", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Standing Reward List", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Item Rewards", None))
        self.StandingAmount.setText("")
        self.StandingAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Standing Amount", None))
        self.SuccessAddStandingToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.SuccessRewardId.setText("")
        self.SuccessRewardId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Item Id", None))
        self.SuccessRewardAmount.setText("")
        self.SuccessRewardAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.SuccessAddItemToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Item Reward List", None))
        self.SuccessAddCurrencyToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Currency", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Currency Reward List", None))
        self.SuccessCurrencyRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.SuccessRemoveStandingFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.SuccessRemoveItemFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.SuccessTrader.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Success 1", None))
        self.AssortTraderItemId.setText("")
        self.AssortTraderItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ItemId", None))
        self.AssortTraderUnlockRemoveFromList.setText(QCoreApplication.translate("MainWindow", u"Remove From List", None))
        self.AssortTraderComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.AssortTraderUnlockAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Assort Reward List", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Assort Unlock", None))
        self.AssortLoyaltyLevelComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Loyalty level", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), QCoreApplication.translate("MainWindow", u"Success 2", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Rewards", None))
        self.CanShowNotifications.setText(QCoreApplication.translate("MainWindow", u"Can Show Notifications", None))
        self.InstantComplete.setText(QCoreApplication.translate("MainWindow", u"Instant Complete", None))
        self.Note.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Note", None))
        self.Side.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Side", None))
        self.QuestName.setText("")
        self.QuestName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest Name", None))
        self._Id.setText("")
        self._Id.setPlaceholderText(QCoreApplication.translate("MainWindow", u"_id", None))
        self.DynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.SuccessMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Success Message (Same as Complete message)", None))
        self.ImagePath.setText(QCoreApplication.translate("MainWindow", u"Placeholder.png", None))
        self.ImagePath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Image Path", None))
        self.RequiresKey.setText(QCoreApplication.translate("MainWindow", u"Requires a Key", None))
        self.Restartable.setText(QCoreApplication.translate("MainWindow", u"Restartable", None))
        self.LoadQuestFile.setText(QCoreApplication.translate("MainWindow", u"Load Quest File", None))
        self.TradercomboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader", None))
        self.LocationComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Location", None))
        self.TraderIdTextField.setText("")
        self.TraderIdTextField.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader Id override", None))
        self.LocationIdTextField.setText("")
        self.LocationIdTextField.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Location Id override", None))
        self.RemoveFromQuestFile.setText(QCoreApplication.translate("MainWindow", u"Remove Quest", None))
        self.EditQuest.setText(QCoreApplication.translate("MainWindow", u"Edit Quest", None))
        self.SaveQuestFile.setText(QCoreApplication.translate("MainWindow", u"Save Quest", None))
        self.NewQuestFile.setText(QCoreApplication.translate("MainWindow", u"New Quest File", None))
        self.LoadFilePath.setText("")
        self.LoadFilePath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Loaded File Path", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Loaded File", None))
        self.LoadedLocalePath.setText("")
        self.LoadedLocalePath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Loaded File Path", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Loaded Locale file", None))
        self.Author.setText(QCoreApplication.translate("MainWindow", u"Author: Dirtbikercj Github Repo:", None))
        self.GithubPath.setText(QCoreApplication.translate("MainWindow", u"https://github.com/dirtbikercj/TarkovTools", None))
        self.GithubPath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Github Path", None))
        self.ALPHAVERSION.setText(QCoreApplication.translate("MainWindow", u"ALPHA VERSION  REPORT ALL BUGS. DO NOT ATTEMPT TO EDIT BSG QUESTS", None))
        self.ClearButton.setText(QCoreApplication.translate("MainWindow", u"Clear All", None))
        self.Author_2.setText(QCoreApplication.translate("MainWindow", u"Warning: Will clear all unsaved progress!", None))
        self.CurrentQuestText.setText("")
        self.CurrentQuestText.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Current Quest", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Current Quest", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Error Console", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Quest Browser", None))
        self.ClearConsole.setText(QCoreApplication.translate("MainWindow", u"Clear Console", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.QuestCreator), QCoreApplication.translate("MainWindow", u"Quest Creator", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Come Back Later!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Item Tool", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Come Back Later!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_17), QCoreApplication.translate("MainWindow", u"Mod Editor", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

