# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'TarkovToolsUYLvtB.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QFrame, QLabel, QLayout, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QStatusBar, QTabWidget,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 980)
        MainWindow.setMinimumSize(QSize(1920, 980))
        MainWindow.setMaximumSize(QSize(1920, 980))
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 9, 1911, 1061))
        self.formLayout = QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.QuestCreator = QWidget()
        self.QuestCreator.setObjectName(u"QuestCreator")
        self.FailMessage = QTextEdit(self.QuestCreator)
        self.FailMessage.setObjectName(u"FailMessage")
        self.FailMessage.setGeometry(QRect(350, 250, 521, 201))
        self.GenerateQuest = QPushButton(self.QuestCreator)
        self.GenerateQuest.setObjectName(u"GenerateQuest")
        self.GenerateQuest.setGeometry(QRect(200, 30, 131, 24))
        self.CompleteMessage = QTextEdit(self.QuestCreator)
        self.CompleteMessage.setObjectName(u"CompleteMessage")
        self.CompleteMessage.setGeometry(QRect(900, 60, 521, 171))
        self.ChangeMessage = QTextEdit(self.QuestCreator)
        self.ChangeMessage.setObjectName(u"ChangeMessage")
        self.ChangeMessage.setGeometry(QRect(900, 470, 521, 201))
        self.SecretQuest = QCheckBox(self.QuestCreator)
        self.SecretQuest.setObjectName(u"SecretQuest")
        self.SecretQuest.setGeometry(QRect(770, 30, 101, 20))
        self.SecretQuest.setChecked(False)
        self.TraderId = QLineEdit(self.QuestCreator)
        self.TraderId.setObjectName(u"TraderId")
        self.TraderId.setGeometry(QRect(1060, 0, 111, 21))
        self.TraderId.setMaxLength(24)
        self.TraderId.setClearButtonEnabled(True)
        self.Description = QTextEdit(self.QuestCreator)
        self.Description.setObjectName(u"Description")
        self.Description.setGeometry(QRect(900, 250, 521, 201))
        self.Type = QComboBox(self.QuestCreator)
        self.Type.setObjectName(u"Type")
        self.Type.setGeometry(QRect(1300, 0, 111, 21))
        self.tabWidget_2 = QTabWidget(self.QuestCreator)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(1440, 0, 461, 881))
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.lineEdit_20 = QLineEdit(self.tab_4)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(9, 862, 132, 21))
        self.lineEdit_20.setClearButtonEnabled(True)
        self.AvailableForStartLevelRequirement = QLineEdit(self.tab_4)
        self.AvailableForStartLevelRequirement.setObjectName(u"AvailableForStartLevelRequirement")
        self.AvailableForStartLevelRequirement.setGeometry(QRect(10, 20, 111, 21))
        self.AvailableForStartLevelRequirementCompare = QComboBox(self.tab_4)
        self.AvailableForStartLevelRequirementCompare.setObjectName(u"AvailableForStartLevelRequirementCompare")
        self.AvailableForStartLevelRequirementCompare.setGeometry(QRect(310, 20, 121, 22))
        self.AvailableForStartQuestView = QScrollArea(self.tab_4)
        self.AvailableForStartQuestView.setObjectName(u"AvailableForStartQuestView")
        self.AvailableForStartQuestView.setGeometry(QRect(0, 130, 441, 151))
        self.AvailableForStartQuestView.setWidgetResizable(True)
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setObjectName(u"scrollAreaWidgetContents_6")
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 439, 149))
        self.AvailableForStartQuestView.setWidget(self.scrollAreaWidgetContents_6)
        self.line_4 = QFrame(self.tab_4)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 40, 451, 20))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.AvailableForStartQuestId = QLineEdit(self.tab_4)
        self.AvailableForStartQuestId.setObjectName(u"AvailableForStartQuestId")
        self.AvailableForStartQuestId.setGeometry(QRect(10, 70, 111, 21))
        self.AvailableForStartAddToList = QPushButton(self.tab_4)
        self.AvailableForStartAddToList.setObjectName(u"AvailableForStartAddToList")
        self.AvailableForStartAddToList.setGeometry(QRect(310, 70, 121, 24))
        self.AvailableForStartDynamicLocaleLevel = QCheckBox(self.tab_4)
        self.AvailableForStartDynamicLocaleLevel.setObjectName(u"AvailableForStartDynamicLocaleLevel")
        self.AvailableForStartDynamicLocaleLevel.setGeometry(QRect(170, 20, 111, 20))
        self.AvailableForStartDynamicLocaleLevel.setChecked(False)
        self.AvailableForStartDynamicLocaleQuest = QCheckBox(self.tab_4)
        self.AvailableForStartDynamicLocaleQuest.setObjectName(u"AvailableForStartDynamicLocaleQuest")
        self.AvailableForStartDynamicLocaleQuest.setGeometry(QRect(170, 70, 111, 20))
        self.AvailableForStartDynamicLocaleQuest.setChecked(False)
        self.line_14 = QFrame(self.tab_4)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(0, 280, 451, 20))
        self.line_14.setFrameShape(QFrame.HLine)
        self.line_14.setFrameShadow(QFrame.Sunken)
        self.AvailableForStartStatus = QComboBox(self.tab_4)
        self.AvailableForStartStatus.setObjectName(u"AvailableForStartStatus")
        self.AvailableForStartStatus.setGeometry(QRect(10, 100, 111, 22))
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 0, 49, 16))
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 111, 16))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.comboBox_6 = QComboBox(self.tab_3)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(9, 852, 68, 21))
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setModelColumn(0)
        self.lineEdit_16 = QLineEdit(self.tab_3)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(9, 879, 132, 21))
        self.lineEdit_16.setClearButtonEnabled(True)
        self.lineEdit_14 = QLineEdit(self.tab_3)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(9, 906, 132, 21))
        self.lineEdit_14.setClearButtonEnabled(True)
        self.checkBox_10 = QCheckBox(self.tab_3)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(9, 933, 212, 20))
        self.checkBox_10.setChecked(False)
        self.tabWidget_5 = QTabWidget(self.tab_3)
        self.tabWidget_5.setObjectName(u"tabWidget_5")
        self.tabWidget_5.setGeometry(QRect(0, 0, 461, 861))
        self.tabWidget_5.setTabBarAutoHide(False)
        self.tab_11 = QWidget()
        self.tab_11.setObjectName(u"tab_11")
        self.FinishLoyaltyId = QLineEdit(self.tab_11)
        self.FinishLoyaltyId.setObjectName(u"FinishLoyaltyId")
        self.FinishLoyaltyId.setGeometry(QRect(10, 20, 121, 21))
        self.label = QLabel(self.tab_11)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 49, 16))
        self.FinishLoyaltyDynamicLocale = QCheckBox(self.tab_11)
        self.FinishLoyaltyDynamicLocale.setObjectName(u"FinishLoyaltyDynamicLocale")
        self.FinishLoyaltyDynamicLocale.setGeometry(QRect(220, 20, 111, 20))
        self.FinishLoyaltyValue = QLineEdit(self.tab_11)
        self.FinishLoyaltyValue.setObjectName(u"FinishLoyaltyValue")
        self.FinishLoyaltyValue.setGeometry(QRect(140, 20, 71, 21))
        self.FinishLoyaltyCompare = QComboBox(self.tab_11)
        self.FinishLoyaltyCompare.setObjectName(u"FinishLoyaltyCompare")
        self.FinishLoyaltyCompare.setGeometry(QRect(330, 20, 121, 22))
        self.line = QFrame(self.tab_11)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-10, 230, 461, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.FinishSkillComboBox = QComboBox(self.tab_11)
        self.FinishSkillComboBox.setObjectName(u"FinishSkillComboBox")
        self.FinishSkillComboBox.setGeometry(QRect(10, 260, 121, 22))
        self.label_2 = QLabel(self.tab_11)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 240, 49, 16))
        self.FinishSkillValue = QLineEdit(self.tab_11)
        self.FinishSkillValue.setObjectName(u"FinishSkillValue")
        self.FinishSkillValue.setGeometry(QRect(140, 260, 71, 21))
        self.FinishDynamicLocaleSkill = QCheckBox(self.tab_11)
        self.FinishDynamicLocaleSkill.setObjectName(u"FinishDynamicLocaleSkill")
        self.FinishDynamicLocaleSkill.setGeometry(QRect(220, 260, 111, 20))
        self.FinishSkillCompare = QComboBox(self.tab_11)
        self.FinishSkillCompare.setObjectName(u"FinishSkillCompare")
        self.FinishSkillCompare.setGeometry(QRect(330, 260, 121, 22))
        self.line_2 = QFrame(self.tab_11)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 470, 461, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.FinishSkillScroll = QScrollArea(self.tab_11)
        self.FinishSkillScroll.setObjectName(u"FinishSkillScroll")
        self.FinishSkillScroll.setGeometry(QRect(0, 320, 451, 151))
        self.FinishSkillScroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 449, 149))
        self.FinishSkillScroll.setWidget(self.scrollAreaWidgetContents_7)
        self.FinishLoyaltyScroll = QScrollArea(self.tab_11)
        self.FinishLoyaltyScroll.setObjectName(u"FinishLoyaltyScroll")
        self.FinishLoyaltyScroll.setGeometry(QRect(0, 80, 451, 151))
        self.FinishLoyaltyScroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_8 = QWidget()
        self.scrollAreaWidgetContents_8.setObjectName(u"scrollAreaWidgetContents_8")
        self.scrollAreaWidgetContents_8.setGeometry(QRect(0, 0, 449, 149))
        self.FinishLoyaltyScroll.setWidget(self.scrollAreaWidgetContents_8)
        self.FinishLoyaltyAddToList = QPushButton(self.tab_11)
        self.FinishLoyaltyAddToList.setObjectName(u"FinishLoyaltyAddToList")
        self.FinishLoyaltyAddToList.setGeometry(QRect(10, 50, 121, 24))
        self.FinishSkillAddToList = QPushButton(self.tab_11)
        self.FinishSkillAddToList.setObjectName(u"FinishSkillAddToList")
        self.FinishSkillAddToList.setGeometry(QRect(10, 290, 121, 24))
        self.FinishItemDynamicLocale = QCheckBox(self.tab_11)
        self.FinishItemDynamicLocale.setObjectName(u"FinishItemDynamicLocale")
        self.FinishItemDynamicLocale.setGeometry(QRect(220, 500, 111, 20))
        self.FinishItemScroll = QScrollArea(self.tab_11)
        self.FinishItemScroll.setObjectName(u"FinishItemScroll")
        self.FinishItemScroll.setGeometry(QRect(0, 560, 451, 151))
        self.FinishItemScroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_11 = QWidget()
        self.scrollAreaWidgetContents_11.setObjectName(u"scrollAreaWidgetContents_11")
        self.scrollAreaWidgetContents_11.setGeometry(QRect(0, 0, 449, 149))
        self.FinishItemScroll.setWidget(self.scrollAreaWidgetContents_11)
        self.FinishItemAddToList = QPushButton(self.tab_11)
        self.FinishItemAddToList.setObjectName(u"FinishItemAddToList")
        self.FinishItemAddToList.setGeometry(QRect(100, 530, 121, 24))
        self.FinishItemAmount = QLineEdit(self.tab_11)
        self.FinishItemAmount.setObjectName(u"FinishItemAmount")
        self.FinishItemAmount.setGeometry(QRect(140, 500, 71, 21))
        self.FinishItemId = QLineEdit(self.tab_11)
        self.FinishItemId.setObjectName(u"FinishItemId")
        self.FinishItemId.setGeometry(QRect(10, 500, 121, 21))
        self.FinishItemFIR = QCheckBox(self.tab_11)
        self.FinishItemFIR.setObjectName(u"FinishItemFIR")
        self.FinishItemFIR.setGeometry(QRect(340, 500, 111, 20))
        self.label_13 = QLabel(self.tab_11)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 480, 101, 16))
        self.FinishItemEncoded = QCheckBox(self.tab_11)
        self.FinishItemEncoded.setObjectName(u"FinishItemEncoded")
        self.FinishItemEncoded.setGeometry(QRect(10, 530, 111, 20))
        self.line_16 = QFrame(self.tab_11)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(-10, 720, 461, 20))
        self.line_16.setFrameShape(QFrame.HLine)
        self.line_16.setFrameShadow(QFrame.Sunken)
        self.tabWidget_5.addTab(self.tab_11, "")
        self.tab_12 = QWidget()
        self.tab_12.setObjectName(u"tab_12")
        self.tabWidget_5.addTab(self.tab_12, "")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget_3 = QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 461, 981))
        self.tabWidget_3.setTabShape(QTabWidget.Rounded)
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_9 = QLabel(self.tab_7)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(9, 9, 57, 16))
        self.StartedAddItemToList = QPushButton(self.tab_7)
        self.StartedAddItemToList.setObjectName(u"StartedAddItemToList")
        self.StartedAddItemToList.setGeometry(QRect(310, 30, 75, 24))
        self.StartedItemId = QLineEdit(self.tab_7)
        self.StartedItemId.setObjectName(u"StartedItemId")
        self.StartedItemId.setGeometry(QRect(10, 30, 132, 21))
        self.StartedItemId.setMaxLength(24)
        self.StartedItemId.setClearButtonEnabled(True)
        self.line_9 = QFrame(self.tab_7)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(9, 50, 441, 16))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.StartedItemAmount = QLineEdit(self.tab_7)
        self.StartedItemAmount.setObjectName(u"StartedItemAmount")
        self.StartedItemAmount.setGeometry(QRect(160, 30, 132, 21))
        self.StartedItemAmount.setMaxLength(24)
        self.StartedItemAmount.setClearButtonEnabled(True)
        self.label_10 = QLabel(self.tab_7)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(9, 60, 57, 16))
        self.StartedItemReward = QScrollArea(self.tab_7)
        self.StartedItemReward.setObjectName(u"StartedItemReward")
        self.StartedItemReward.setGeometry(QRect(10, 80, 441, 821))
        self.StartedItemReward.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 439, 819))
        self.StartedItemReward.setWidget(self.scrollAreaWidgetContents_4)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.ExperienceAmount = QLineEdit(self.tab_8)
        self.ExperienceAmount.setObjectName(u"ExperienceAmount")
        self.ExperienceAmount.setGeometry(QRect(9, 9, 132, 21))
        self.ExperienceAmount.setMaxLength(24)
        self.ExperienceAmount.setClearButtonEnabled(True)
        self.CurrencyAmount = QLineEdit(self.tab_8)
        self.CurrencyAmount.setObjectName(u"CurrencyAmount")
        self.CurrencyAmount.setGeometry(QRect(170, 60, 132, 21))
        self.CurrencyAmount.setMaxLength(24)
        self.CurrencyAmount.setClearButtonEnabled(True)
        self.CurrencyType = QComboBox(self.tab_8)
        self.CurrencyType.setObjectName(u"CurrencyType")
        self.CurrencyType.setGeometry(QRect(10, 60, 131, 21))
        self.CurrencyType.setEditable(False)
        self.CurrencyType.setModelColumn(0)
        self.line_5 = QFrame(self.tab_8)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(9, 240, 437, 16))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.tab_8)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(9, 250, 84, 16))
        self.label_7 = QLabel(self.tab_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(9, 300, 111, 16))
        self.line_6 = QFrame(self.tab_8)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(9, 290, 437, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.tab_8)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(9, 570, 72, 16))
        self.StandingAmount = QLineEdit(self.tab_8)
        self.StandingAmount.setObjectName(u"StandingAmount")
        self.StandingAmount.setGeometry(QRect(170, 270, 132, 21))
        self.StandingAmount.setMaxLength(24)
        self.StandingAmount.setClearButtonEnabled(True)
        self.SuccessTraderIdStanding = QLineEdit(self.tab_8)
        self.SuccessTraderIdStanding.setObjectName(u"SuccessTraderIdStanding")
        self.SuccessTraderIdStanding.setGeometry(QRect(9, 270, 132, 21))
        self.SuccessTraderIdStanding.setMaxLength(24)
        self.SuccessTraderIdStanding.setClearButtonEnabled(True)
        self.line_7 = QFrame(self.tab_8)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(9, 610, 437, 16))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.SuccessAddStandingToList = QPushButton(self.tab_8)
        self.SuccessAddStandingToList.setObjectName(u"SuccessAddStandingToList")
        self.SuccessAddStandingToList.setGeometry(QRect(330, 270, 121, 24))
        self.SuccessRewardId = QLineEdit(self.tab_8)
        self.SuccessRewardId.setObjectName(u"SuccessRewardId")
        self.SuccessRewardId.setGeometry(QRect(9, 590, 132, 21))
        self.SuccessRewardId.setMaxLength(24)
        self.SuccessRewardId.setClearButtonEnabled(True)
        self.SuccessRewardAmount = QLineEdit(self.tab_8)
        self.SuccessRewardAmount.setObjectName(u"SuccessRewardAmount")
        self.SuccessRewardAmount.setGeometry(QRect(162, 590, 132, 21))
        self.SuccessRewardAmount.setMaxLength(24)
        self.SuccessRewardAmount.setClearButtonEnabled(True)
        self.SuccessAddItemToList = QPushButton(self.tab_8)
        self.SuccessAddItemToList.setObjectName(u"SuccessAddItemToList")
        self.SuccessAddItemToList.setGeometry(QRect(314, 590, 131, 24))
        self.line_8 = QFrame(self.tab_8)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(9, 560, 437, 16))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.SuccessTraderReward = QScrollArea(self.tab_8)
        self.SuccessTraderReward.setObjectName(u"SuccessTraderReward")
        self.SuccessTraderReward.setGeometry(QRect(9, 320, 441, 231))
        self.SuccessTraderReward.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 439, 229))
        self.SuccessTraderReward.setWidget(self.scrollAreaWidgetContents_2)
        self.SuccessItemReward = QScrollArea(self.tab_8)
        self.SuccessItemReward.setObjectName(u"SuccessItemReward")
        self.SuccessItemReward.setGeometry(QRect(9, 640, 431, 201))
        self.SuccessItemReward.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 429, 199))
        self.SuccessItemReward.setWidget(self.scrollAreaWidgetContents_3)
        self.label_5 = QLabel(self.tab_8)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(9, 620, 88, 16))
        self.SuccessAddCurrencyToList = QPushButton(self.tab_8)
        self.SuccessAddCurrencyToList.setObjectName(u"SuccessAddCurrencyToList")
        self.SuccessAddCurrencyToList.setGeometry(QRect(330, 60, 121, 24))
        self.line_12 = QFrame(self.tab_8)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(10, 30, 437, 16))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.label_11 = QLabel(self.tab_8)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 40, 84, 16))
        self.line_13 = QFrame(self.tab_8)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(10, 80, 437, 16))
        self.line_13.setFrameShape(QFrame.HLine)
        self.line_13.setFrameShadow(QFrame.Sunken)
        self.SuccessCurrencyReward = QScrollArea(self.tab_8)
        self.SuccessCurrencyReward.setObjectName(u"SuccessCurrencyReward")
        self.SuccessCurrencyReward.setGeometry(QRect(10, 110, 441, 121))
        self.SuccessCurrencyReward.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 439, 119))
        self.SuccessCurrencyReward.setWidget(self.scrollAreaWidgetContents_5)
        self.label_12 = QLabel(self.tab_8)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 90, 111, 16))
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_4 = QTabWidget(self.tab)
        self.tabWidget_4.setObjectName(u"tabWidget_4")
        self.tabWidget_4.setGeometry(QRect(0, 0, 451, 971))
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tabWidget_2.addTab(self.tab, "")
        self.CanShowNotifications = QCheckBox(self.QuestCreator)
        self.CanShowNotifications.setObjectName(u"CanShowNotifications")
        self.CanShowNotifications.setGeometry(QRect(900, 30, 146, 20))
        self.CanShowNotifications.setChecked(True)
        self.InstantComplete = QCheckBox(self.QuestCreator)
        self.InstantComplete.setObjectName(u"InstantComplete")
        self.InstantComplete.setGeometry(QRect(1300, 30, 114, 20))
        self.InstantComplete.setChecked(False)
        self.Note = QTextEdit(self.QuestCreator)
        self.Note.setObjectName(u"Note")
        self.Note.setGeometry(QRect(350, 470, 521, 201))
        self.StartedMessage = QTextEdit(self.QuestCreator)
        self.StartedMessage.setObjectName(u"StartedMessage")
        self.StartedMessage.setGeometry(QRect(350, 690, 521, 191))
        self.Side = QComboBox(self.QuestCreator)
        self.Side.setObjectName(u"Side")
        self.Side.setGeometry(QRect(1190, 0, 81, 21))
        self.Side.setEditable(False)
        self.Side.setModelColumn(0)
        self.QuestName = QLineEdit(self.QuestCreator)
        self.QuestName.setObjectName(u"QuestName")
        self.QuestName.setGeometry(QRect(350, 0, 251, 21))
        self.QuestName.setClearButtonEnabled(True)
        self.AcceptMessage = QTextEdit(self.QuestCreator)
        self.AcceptMessage.setObjectName(u"AcceptMessage")
        self.AcceptMessage.setGeometry(QRect(350, 60, 521, 171))
        self._Id = QLineEdit(self.QuestCreator)
        self._Id.setObjectName(u"_Id")
        self._Id.setGeometry(QRect(630, 0, 241, 21))
        self._Id.setMaxLength(24)
        self._Id.setClearButtonEnabled(True)
        self.DynamicLocale = QCheckBox(self.QuestCreator)
        self.DynamicLocale.setObjectName(u"DynamicLocale")
        self.DynamicLocale.setGeometry(QRect(630, 30, 111, 20))
        self.DynamicLocale.setChecked(False)
        self.SuccessMessage = QTextEdit(self.QuestCreator)
        self.SuccessMessage.setObjectName(u"SuccessMessage")
        self.SuccessMessage.setGeometry(QRect(900, 690, 521, 191))
        self.ImagePath = QLineEdit(self.QuestCreator)
        self.ImagePath.setObjectName(u"ImagePath")
        self.ImagePath.setGeometry(QRect(350, 30, 251, 21))
        self.ImagePath.setMaxLength(512)
        self.ImagePath.setClearButtonEnabled(True)
        self.RequiresKey = QCheckBox(self.QuestCreator)
        self.RequiresKey.setObjectName(u"RequiresKey")
        self.RequiresKey.setGeometry(QRect(1060, 30, 100, 20))
        self.Location = QLineEdit(self.QuestCreator)
        self.Location.setObjectName(u"Location")
        self.Location.setGeometry(QRect(900, 0, 141, 21))
        self.Location.setClearButtonEnabled(True)
        self.Restartable = QCheckBox(self.QuestCreator)
        self.Restartable.setObjectName(u"Restartable")
        self.Restartable.setGeometry(QRect(1190, 30, 82, 20))
        self.Restartable.setChecked(False)
        self.QuestSelection = QScrollArea(self.QuestCreator)
        self.QuestSelection.setObjectName(u"QuestSelection")
        self.QuestSelection.setGeometry(QRect(10, 60, 321, 821))
        self.QuestSelection.setAutoFillBackground(False)
        self.QuestSelection.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 319, 819))
        self.QuestSelection.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QLineEdit(self.QuestCreator)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(9, 0, 321, 21))
        self.pushButton = QPushButton(self.QuestCreator)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(9, 30, 131, 24))
        self.line_10 = QFrame(self.QuestCreator)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(340, -20, 3, 1080))
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.QuestCreator)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(1430, -20, 3, 1080))
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.tabWidget.addTab(self.QuestCreator, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Tarkov Tools 0.0.1", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.FailMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Fail Message", None))
        self.GenerateQuest.setText(QCoreApplication.translate("MainWindow", u"Generate Quest", None))
        self.CompleteMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Complete Message", None))
        self.ChangeMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Change Message", None))
        self.SecretQuest.setText(QCoreApplication.translate("MainWindow", u"Secret Quest", None))
        self.TraderId.setText("")
        self.TraderId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader Id", None))
        self.Description.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.Type.setCurrentText("")
        self.Type.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.lineEdit_20.setText("")
        self.lineEdit_20.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Available After", None))
        self.AvailableForStartLevelRequirement.setInputMask("")
        self.AvailableForStartLevelRequirement.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.AvailableForStartLevelRequirement.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Level requirement", None))
        self.AvailableForStartLevelRequirementCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.AvailableForStartQuestId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest Id", None))
        self.AvailableForStartAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.AvailableForStartDynamicLocaleLevel.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.AvailableForStartDynamicLocaleQuest.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.AvailableForStartStatus.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Quest Requirement", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Available For Start", None))
        self.comboBox_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Side", None))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.lineEdit_14.setText("")
        self.lineEdit_14.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Index", None))
        self.checkBox_10.setText(QCoreApplication.translate("MainWindow", u"Do Not Reset If Counter Completed", None))
        self.FinishLoyaltyId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader Id", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Loyalty", None))
        self.FinishLoyaltyDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FinishLoyaltyValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.FinishLoyaltyCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.FinishSkillComboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Skill", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Skill", None))
        self.FinishSkillValue.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Value", None))
        self.FinishDynamicLocaleSkill.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FinishSkillCompare.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Compare Method", None))
        self.FinishLoyaltyAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishSkillAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishItemDynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.FinishItemAddToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.FinishItemAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.FinishItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ItemId", None))
        self.FinishItemFIR.setText(QCoreApplication.translate("MainWindow", u"Found in raid", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Find Items</p></body></html>", None))
        self.FinishItemEncoded.setText(QCoreApplication.translate("MainWindow", u"IsEncoded", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_11), QCoreApplication.translate("MainWindow", u"Loyalty, Skills, Items", None))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), QCoreApplication.translate("MainWindow", u"Location", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Available For Finish", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Fail", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Start Items", None))
        self.StartedAddItemToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.StartedItemId.setText("")
        self.StartedItemId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Item Id", None))
        self.StartedItemAmount.setText("")
        self.StartedItemAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Start Items", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Started", None))
        self.ExperienceAmount.setText("")
        self.ExperienceAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Experience Amount", None))
        self.CurrencyAmount.setText("")
        self.CurrencyAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Currency Amount", None))
        self.CurrencyType.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Currency Type", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Trader Standing", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Standing Reward List", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Item Rewards", None))
        self.StandingAmount.setText("")
        self.StandingAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Standing Amount", None))
        self.SuccessTraderIdStanding.setText("")
        self.SuccessTraderIdStanding.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Trader Id", None))
        self.SuccessAddStandingToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.SuccessRewardId.setText("")
        self.SuccessRewardId.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Item Id", None))
        self.SuccessRewardAmount.setText("")
        self.SuccessRewardAmount.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Amount", None))
        self.SuccessAddItemToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Item Reward List", None))
        self.SuccessAddCurrencyToList.setText(QCoreApplication.translate("MainWindow", u"Add To List", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Currency", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Currency Reward List", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Success", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Rewards", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Quest.Json", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Locale.json", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Json", None))
        self.CanShowNotifications.setText(QCoreApplication.translate("MainWindow", u"Can Show Notifications", None))
        self.InstantComplete.setText(QCoreApplication.translate("MainWindow", u"Instant Complete", None))
        self.Note.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Note", None))
        self.StartedMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Started Message", None))
        self.Side.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Side", None))
        self.QuestName.setText("")
        self.QuestName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest Name", None))
        self.AcceptMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Accept Message", None))
        self._Id.setText("")
        self._Id.setPlaceholderText(QCoreApplication.translate("MainWindow", u"_id", None))
        self.DynamicLocale.setText(QCoreApplication.translate("MainWindow", u"Dynamic Locale", None))
        self.SuccessMessage.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Success Message", None))
        self.ImagePath.setText("")
        self.ImagePath.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Image Path", None))
        self.RequiresKey.setText(QCoreApplication.translate("MainWindow", u"Requires a Key", None))
        self.Location.setText("")
        self.Location.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Location", None))
        self.Restartable.setText(QCoreApplication.translate("MainWindow", u"Restartable", None))
#if QT_CONFIG(tooltip)
        self.QuestSelection.setToolTip(QCoreApplication.translate("MainWindow", u"Quests in the loaded file appear here.", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quest File Path", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Load Quest File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.QuestCreator), QCoreApplication.translate("MainWindow", u"Quest Creator", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Item Tool", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

